package io.github.mattpvaughn.chronicle.util

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The framework-free core, and a fence around it (cu-177).
 *
 * **87 files carry no `android.*` or `androidx.*` import** beyond Room annotations. They are not a
 * curiosity — they are the decision logic: `SleepTimerState`, `ChapterSeekTarget`,
 * `CacheReconciliation`, `IngestionPlan`, `BookSearch`, `SeriesIndexPatterns`, all five
 * repositories, `DurationFormat`.
 *
 * Measured 2026-09-06, and the reason this guard exists:
 *
 * | | coverage |
 * |---|---:|
 * | these files | **80.8%** |
 * | everything else | 35.7% |
 *
 * A file that can be tested without a framework *gets* tested. That purity was not designed in one
 * go — it is what cu-19, cu-21, cu-101, cu-136 and cu-176 each produced by pulling a decision out
 * of a framework class — and nothing but review currently stops someone adding
 * `import android.os.Bundle` to `SleepTimerState` tomorrow. The 2026-09-05 review found that
 * review misses things.
 *
 * **Room annotations are permitted.** `@Entity`, `@PrimaryKey`, `@TypeConverter` and friends are
 * compile-time metadata that a pure Kotlin module keeps — Room supports exactly this — and
 * excluding the entities would drop the models this guard most wants to protect.
 *
 * The list is **committed, not computed**. Deriving it at test time would let a newly-impure file
 * silently drop out and the test still pass, which is the failure mode that makes a guard
 * worthless. Adding a file here is free; removing one should carry a comment saying what framework
 * dependency it grew and why that was the right call.
 *
 * This is a `:domain` Gradle module's enforcement without the module. Whether to take the module
 * itself is recorded in `backlog/docs/analysis/maintainability-review-2026-09.md`: it would buy
 * enforcement, a faster pure build and two honest coverage signals instead of one blended figure —
 * but **not** testability, since these files are already at 80.8%.
 */
class FrameworkFreeCoreTest {
  @Test
  fun `every file on the list is still framework-free`() {
    val offenders =
      FRAMEWORK_FREE.mapNotNull { relative ->
        val file = File("$SOURCE_ROOT/$relative")
        if (!file.isFile) return@mapNotNull "$relative (missing — moved or renamed?)"
        val bad =
          file.readLines()
            .filter { it.startsWith("import android.") || it.startsWith("import androidx.") }
            .filterNot { it.startsWith("import androidx.room") }
        if (bad.isEmpty()) null else "$relative -> ${bad.joinToString()}"
      }

    assertTrue(
      "These files are on the framework-free list but now import the Android framework.\n" +
        "Either move the framework-facing part out (as cu-176 did for the media conversions), or " +
        "remove the file from the list with a comment saying why:\n" +
        offenders.joinToString("\n"),
      offenders.isEmpty(),
    )
  }

  /** A guard whose list has quietly emptied proves nothing. */
  @Test
  fun `the list is not empty and the source root resolves`() {
    assertTrue("source root not found at $SOURCE_ROOT", File(SOURCE_ROOT).isDirectory)
    assertTrue("the framework-free list is suspiciously short", FRAMEWORK_FREE.size > 50)
  }

  private companion object {
    const val SOURCE_ROOT = "src/main/java/io/github/mattpvaughn/chronicle"

    /**
     * Files with no framework import, generated by measurement and then committed.
     *
     * Keep sorted; add freely, remove only with a reason.
     */
    val FRAMEWORK_FREE =
      listOf(
        "application/Constants.kt",
        "data/local/BookRepository.kt",
        "data/local/BookmarkRepository.kt",
        "data/local/CollectionsRepository.kt",
        "data/local/LibrarySyncRepository.kt",
        "data/local/SeriesIndexRulesLoader.kt",
        "data/local/SettingsBackup.kt",
        "data/local/TrackRepository.kt",
        "data/local/ViewStyle.kt",
        "data/model/Audiobook.kt",
        "data/model/BookFacets.kt",
        "data/model/BookSearch.kt",
        "data/model/BookSearchRow.kt",
        "data/model/BookSortComparators.kt",
        "data/model/BookTrackData.kt",
        "data/model/Bookmark.kt",
        "data/model/ChapterAssembly.kt",
        "data/model/Collection.kt",
        "data/model/LoadingStatus.kt",
        "data/model/MediaId.kt",
        "data/model/Offsets.kt",
        "data/model/PlexLibrary.kt",
        "data/model/SeriesIndexDiagnostics.kt",
        "data/model/SeriesIndexPatterns.kt",
        "data/model/SeriesIndexRulesFile.kt",
        "data/model/ServerModel.kt",
        "data/model/SourceId.kt",
        "data/sources/HttpMediaSource.kt",
        "data/sources/IngestionPlan.kt",
        "data/sources/SourceCapabilities.kt",
        "data/sources/SourceManager.kt",
        "data/sources/plex/AccountAuthState.kt",
        "data/sources/plex/ConnectionChooser.kt",
        "data/sources/plex/Constants.kt",
        "data/sources/plex/DeviceAuthorizationCheck.kt",
        "data/sources/plex/MultiIdBatching.kt",
        "data/sources/plex/PlaybackSession.kt",
        "data/sources/plex/PlexService.kt",
        "data/sources/plex/PlexTokenAuthenticator.kt",
        "data/sources/plex/PlexUtils.kt",
        "data/sources/plex/ProgressReporter.kt",
        "data/sources/plex/RedactingFetchLogger.kt",
        "data/sources/plex/TagIndexSeeder.kt",
        "data/sources/plex/model/AudnexusTags.kt",
        "data/sources/plex/model/Feature.kt",
        "data/sources/plex/model/MediaProvider.kt",
        "data/sources/plex/model/MediaType.kt",
        "data/sources/plex/model/OAuthResponse.kt",
        "data/sources/plex/model/PlexChapter.kt",
        "data/sources/plex/model/PlexDevice.kt",
        "data/sources/plex/model/PlexDirectory.kt",
        "data/sources/plex/model/PlexMediaContainer.kt",
        "data/sources/plex/model/PlexServer.kt",
        "data/sources/plex/model/TrackPlexModel.kt",
        "features/bookdetails/BookMetadataLines.kt",
        "features/currentlyplaying/CurrentlyPlayingSingleton.kt",
        "features/currentlyplaying/PlayerText.kt",
        "features/download/CacheReconciliation.kt",
        "features/download/CacheScanOutcome.kt",
        "features/download/DownloadGroupId.kt",
        "features/download/FetchGroupStartFinishListener.kt",
        "features/download/ResumePlan.kt",
        "features/player/CastEligibility.kt",
        "features/player/CastMediaItems.kt",
        "features/player/ChapterSeekTarget.kt",
        "features/player/NotificationRebuild.kt",
        "features/player/OutgoingBookFlush.kt",
        "features/player/PlaybackErrorDescription.kt",
        "features/player/ScrubberWindow.kt",
        "features/player/SleepTimerState.kt",
        "features/player/TrackFetchAttempt.kt",
        "features/player/TrackListStateManager.kt",
        "features/search/SearchController.kt",
        "features/search/SearchRow.kt",
        // `features/settings/PreferenceBindingAdapters.kt` was here until cu-199. It is deleted,
        // not moved: it was a one-function bridge to `SettingsList.setPreferences`, called from
        // nowhere, and both went with the Compose migration of the settings screen. Removed from
        // the list rather than left to fail as "missing", which is what this guard reports for a
        // deleted entry.
        "features/settings/PreferenceModel.kt",
        "util/DispatcherProvider.kt",
        "util/DurationFormat.kt",
        "util/FlowCombinators.kt",
        "util/LifecycleExt.kt",
        "util/ListIdentity.kt",
        "views/ChipGroupExt.kt",
        "views/SpeedChooserState.kt",
      )
  }
}
